/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v1/ack': {
        post: operations['Ack'];
    };
    '/v1/connect': {
        post: operations['Connect'];
    };
    '/v1/init': {
        post: operations['Init'];
    };
    '/v1/send': {
        post: operations['Init'];
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        IAckResponse: {
            error?: {
                message: string;
            };
        };
        IAckRequest: {
            messageId: string;
        };
        IConnectResponse: {
            error?: {
                message: string;
            };
            key: string;
        };
        IConnectRequest: {
            nonce: string;
            data: string;
            to: string;
            pushToken: string;
            key: string;
        };
        IInitResponse: {
            error?: {
                message: string;
            };
            id: string;
            key: string;
        };
        IInitRequest: {
            pushToken: string;
            key: string;
        };
        ISendResponse: {
            error?: {
                message: string;
            };
            ok: boolean;
        };
        ISendRequest: {
            to: string;
            from: string;
            data: string;
            nonce: string;
        };
    };
    responses: {};
    parameters: {};
    requestBodies: {};
    headers: {};
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
    Ack: {
        requestBody: {
            content: {
                'application/json': components['schemas']['IAckRequest'];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                content: {
                    'application/json': components['schemas']['IAckResponse'];
                };
            };
        };
    };
    Connect: {
        requestBody: {
            content: {
                'application/json': components['schemas']['IConnectRequest'];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                content: {
                    'application/json': components['schemas']['IConnectResponse'];
                };
            };
        };
    };
    Init: {
        requestBody: {
            content: {
                'application/json': components['schemas']['ISendRequest'];
            };
        };
        responses: {
            /** @description OK */
            200: {
                content: {
                    'application/json': components['schemas']['ISendResponse'];
                };
            };
        };
    };
}
