#!/bin/bash

# Function to create and initialize an env file
create_env_file() {
  local env_file=$1
  local is_prod=$2
  local ip_address=$(hostname -I | awk '{print $1}')

  if [ ! -f "$env_file" ]; then
    echo "# This file has been generated by scripts/postinstall.sh\n" > "$env_file"
    echo "PLASMO_CRX_ID=TODO" >> "$env_file"
    echo "PLASMO_CRX_CRX_PUBLIC_KEY=TODO" >> "$env_file"
    echo "PLASMO_PUBLIC_FIREBASE_API_KEY=TODO" >> "$env_file"

    if [ "$is_prod" = false ]; then
      echo "PLASMO_PUBLIC_SERVER_URL=http://$ip_address:5001/lockwire-9561c/us-central1/api" >> "$env_file"
    else
      echo "PLASMO_PUBLIC_SERVER_URL=TODO" >> "$env_file"
    fi

    echo "Generated $env_file file. Don't forget to insert required values."
  fi
}

# Main script starts here
DEV_ENV_FILE="$(pwd)/.env"
PROD_ENV_FILE="$(pwd)/.env.prod"

create_env_file "$DEV_ENV_FILE" false
create_env_file "$PROD_ENV_FILE" true
